### ISSUE TITLE
bundle installするとrailsのバージョンが異なる

### ISSUE THREAD

**Issue by konjikicity** [running-23/pickable#17]
## 概要
現在のGemfile.Gemfile.lockを使用し、`bundle install`すると`rails 6.1.4.6`がインストールされる。

## 考えられる原因
https://github.com/running-23/pickable/blob/56c07477391dc3267faea98b7294d2512a9735e3/Gemfile#L7
・この記述が`'=> 6.1.4.4'`以降で最新のものがインストールされるので`rails 6.1.4.6`がインストールされる？

・自分のローカルの問題 : 調査中

## やったこと
・bundlerを2.3.8へ
・rbenvのrubyを再インストール
## 改善
Gemfileの記述を`rails, '6.1.4.4'`で固定してGemfile.lockを削除した。
その後bundle installしたらrailsのバージョンは`6.1.4.4`になったが...

## コメント
ローカルの原因なのかどうかがわからない状態なので
みなさんのローカルの状態はどうなっているのかが知りたいです。
GemfileとGemfile.lockはみなさんに影響する部分ですし
バージョンは固定しない方がいいみたいなのでどうするのが最善かもわからない状態です。

https://nanayaku.com/gem-version/
バージョン固定　参考

**Comment by jibiking** [comment]
お疲れ様です！
改めて自分の環境を確認してみたら、僕も6.1.4.6でした。
小野田さんのおっしゃる通り、おそらく固定しないと最新バージョンになっているのかと思います。
添付していただいた記事の通り、バージョン指定しないで最新バージョンで進める方向で問題ないと思います！
念の為、他の方のご意見も伺いたいです！

**Comment by tarakish** [comment]
遅くなりました！
自分も再確認すると6.1.4.6でした…
環境構築している段階で気づかぬ内にバージョンが上がっていたのだと思われます。
確認不足で混乱させてしまい申し訳ございません！🙇🏻‍♂️

現状リモートの最新のmainブランチが6.1.4.6なので、「そのバージョンで合わせる＆ver.の固定はしない」がスムーズかつ分かりやすいかと思いました！

**Comment by Mokosu-bit** [comment]
お疲れ様です！
自分も確認すると6.1.4.6でした。
バージョン指定せず最新バージョンで進める方向で問題ないと思います！

**Comment by konjikicity** [comment]
了解しました！みなさんありがとうございます！
最新バージョンで作業していきます！
