### ISSUE TITLE
同じファイルを同時平行して作業するとconcriftを起こす場合の対処

### ISSUE THREAD

**Issue by konjikicity** [running-23/pickable#22]
## 概要
同じファイルを同時平行して作業するとconcriftを起こしてしまう対処を考える

## 詳細
今回Eventsテーブルが作成された後にUsersテーブルの作成および、model.ja.ymlを作成したので
`model.ja.yml`と`schema.rb`がconcriftを起こした

## 対処
今回はgithub上で最終なってほしい状態に編集してconcriftを回避した
https://github.com/running-23/pickable/blob/101c11b2d6761d967501f417bb30d667ed2f6c5f/db/schema.rb#L14-L45
https://github.com/running-23/pickable/blob/101c11b2d6761d967501f417bb30d667ed2f6c5f/config/locales/model.ja.yml#L1-L39

## コメント
この対処で大丈夫だったか？やり方を統一したほうがいいかご意見をお伺いしたいです。

**Comment by tarakish** [comment]
`model.ja.yml`に関しては上記対応で問題ないと思います！
自分も月曜日話題に上がった際には完全に忘れていたのですが
`schema.rb`は手動で編集するのは良くなさそうなのでちょっと調べてみます！

**Comment by Mokosu-bit** [comment]
宮本さんと同じく`model.ja.yml`に関しては上記対応で問題ないと思います！
`schema.rb`は宮本さんコメントの記事のように手動ではない方法がよさそうですね！
あとはマージする前に`git fetch`で最新情報を取得して確認するとかですかね🤔
[チーム開発必須！git clone, fetch, pullを解説](https://beyondjapan.com/blog/2021/09/git-clone-pull-fetch/)

**Comment by konjikicity** [comment]
コメントありがとうございます！
複数方法があるみたいだったので迷ってしまいました....
`schema.rb`を手動はまずかったですね...申し訳ないです。
次回以降は宮本さんの記事で対応しようと思います！すいません！

**Comment by tarakish** [comment]
全然です！想定が足りておらずこちらこそ申し訳ないです！🙇🏻‍♂️
今のリモートのmainブランチ、こちらでもローカルで確認してみます！
