### ISSUE TITLE
herokuデプロイ時エラー解消

### ISSUE THREAD

**Issue by Mokosu-bit** [running-23/pickable#25]
### 概要
herokuにpush後、以下のエラーが発生しました。（一部）
[![Image from Gyazo](https://i.gyazo.com/40edfb39af63549387aa49e3989624b1.png)](https://gyazo.com/40edfb39af63549387aa49e3989624b1)

### 原因
`Before process_action callback :require_login has not been defined (ArgumentError)`
で検索したところ`sorcery`が関係してるっぽい。
> 同一ファイル内にcallback関数がない場合、raiseオプションにfalseを設定しないと、ArgumentErrorが出るように変更された。sorceryのcallbackを使うところで変更が必要になった。

### 試そうと考えていること
`user.rb`に以下を追加
```
skip_before_action :require_login, only: %i[new create], raise: false
```

### 確認方法
ターミナルで以下のコマンドを実行
```
heroku logs --tail
```

### 参考
- [ArgumentError](https://qiita.com/fujitora/items/0fd67023b60703894ba5)
-  [Railsを5.0にupdateしたときのメモ](https://tkmr.hatenablog.com/entry/2016/12/21/184334)
- [【Rails5】今更ながらRails4からRails5へのアップグレードをどうやっていくのが良いか調べてみた](https://qiita.com/himrock922/items/0e98e6bd7a50fdb4ed33)

### コメント
対応する前に、ご意見をいただきたいです！

**Comment by jibiking** [comment]
ググっても記事が全然ないので確たることは言えないのですが、、、
```users_controller.rb```の```skip_before_action```に```raise: false```を追加する方向で問題ないかと思います！

```heroku db:migrate```は実施済みですよね？？

**Comment by Mokosu-bit** [comment]
コメントありがとうございます

> ググっても記事が全然ないので確たることは言えないのですが、、、 `users_controller.rb`の`skip_before_action`に`raise: false`を追加する方向で問題ないかと思います！



> `heroku db:migrate`は実施済みですよね？？

`heroku db:migrate`は実行してます！
