### ISSUE TITLE
enum定義の命名について

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#31]
## 概要
`user.rb`にてenum定義している`accept_random`の値について、irbでデバッグした際に下記の警告が出ました。
![スクリーンショット 2022-03-18 23 03 49](https://user-images.githubusercontent.com/71510236/159026890-a6311654-9d39-4c5a-a37f-f6d578c2e337.png)
DeepLの翻訳をそのまま載せると
> スコープ :not_accepted を作成しました。既存のメソッド User.not_accepted を上書き。
User の Enum 要素 'not_accepted' は接頭辞 'not_' を使用しています。このため、自動生成される負のスコープと衝突することがありました。正形が要素である場合、'not' で始まる enum 要素の使用は避けてください。
 
簡単に言うと、notで始まるenum定義をすると良くないみたいです。
こちらで否定、否認の意味のある「deny」を使って修正したところ警告は消えました。
```ruby
enum accept_random: { accepted: 0, denied: 1 }
```
この命名について皆さんのご意見いただけると助かります！

**Comment by jibiking** [comment]
> enum accept_random: { accepted: 0, denied: 1 }
こちらの命名で問題ないと思います🙆‍♂️

**Comment by Mokosu-bit** [comment]
> enum accept_random: { accepted: 0, denied: 1 }

`denied`で問題ないです🙆‍♂️

**Comment by konjikicity** [comment]
これは知らなかったです....`denied`で問題ないと思います！
