### ISSUE TITLE
githubログインを実装後の懸念点

### ISSUE THREAD

**Issue by konjikicity** [running-23/pickable#36]
## 概要
githubログインを実装したが懸念点が主に3点ありました！

### 1. ログインページについて
ログインページが現在[画面遷移図](https://www.figma.com/file/MDG2PmmSNAQeeXRj0lDXZ1/Pickable?node-id=0%3A1)には存在しておりログインまでの流れは
`topページ`→`ログインページ`→`githubログインボタンを押す`だが
ログインページに遷移させる意味があまりない

改善案
topページにgithubログインボタンを設置すればログインページが必要なくなる

### 2. userのnameカラムについて
現在githubログインの認証にnameカラムを使用しており、新規ユーザーが認証されると
githubに対応するカラムにデータが入り、DBに登録される。
ただそうなるとユーザー名の変更ができないのと、github名を表示することになるがわかりずらい名前の人も多い

改善案
sorceryの設定でgithubと紐づくカラムを変更できるので新たにカラムを作成する
名前の編集もこれによりできるようになる

### 3. mottermost_idについて
19722f7 の修正内容を説明すると
github認証してuserがDBに登録されるときはgithubに対応するカラムにしかデータが入らないので
mottermost_idはnilになる。validationで`presence: true`, DBでnot_null制約をつけているため
UserがDBに登録することができなかったエラーを修正しているものである。

こちらの改善案はご意見をお伺いしたいです。

以上３点が懸念した部分となります！

## ToDo

- [x] ログインページの削除
- [x] usersテーブルにgithub_nameカラムを追加
- [x] mottermost_idカラムを削除

**Comment by jibiking** [comment]
１と２
小野田さんがご提案した改善案の通りで問題ないかと思います！

３
- マタモidは修正していただいた通り空にしておいて、ユーザーの名前を設定する画面（user#edit)で設定できるようにすればいいかと思います！
- 「GitHubログイン→ユーザー設定」に遷移で名前＆マタモidを設定できるのがベスト？
- マタモidが必須というバリデーションはviewでつけるしかなさそう（[参考](https://qiita.com/oh_rusty_nail/items/e08f6b323d526fab3d55)）

**Comment by Mokosu-bit** [comment]
1と2の改善案いいと思います！

3に関しては、そもそもリリース時になしにするのもありかと思います！
- マタモidをユーザーに登録してもらうのは手間。
- GitHubログインで取得できる`e-mail`で通知する。（後に反応を見て、マタモ通知にするか決める）

地引さんコメントの「GitHubログイン→ユーザー設定」に遷移で名前設定は必須だと思いました！

**Comment by tarakish** [comment]
問題点と改善案までありがとうございます…！
自分も、1,2に関しては改善案で進める方向でいいと思いました！🙆🏻‍♂️

3に関しては、ディスコードでお話しした際に #21 でメモったんですが結論としては森本さんと同じく
- カラムを削除するか、もしくは
- 修正いただいたnull許容で用意だけしておいて、後々アップデートとしてマタモへ通知できる機能を追加するまで入力させないようにしておく
みたいな感じが自分は現状良いのかなと思います！MTGで話しましょう！笑
