### ISSUE TITLE
rubocopの指摘事項について

### ISSUE THREAD

**Issue by konjikicity** [running-23/pickable#37]
## 概要
githubログインを実装時に新たに指摘された部分について

## 詳細
![00ba0d49540842826a630e6cabc2c8f6](https://user-images.githubusercontent.com/82688205/159291666-0fc0fcc0-7ceb-429f-a37b-d725e0703714.png)

画像一番上の指摘事項以外は修正対応しています。

一番上は一行の文字数の制限を超えているので怒られていますが
どう修正すればいいか迷ったので保留としています。こちらのご意見をお伺いしたいです

**Comment by jibiking** [comment]
解決策
Time.current..Time.current.since(3.years)の部分をモジュール化して取り込むとか、、？

たいした長さではないのでこのままでもいいのでは？と思ってしまうのですが、他の方のご意見も伺いたいです🙇‍♂️

**Comment by tarakish** [comment]
自分も指摘されましたが、単純なwhere句なので後々scopeで切り出してモデルに移したらいいかなくらいで考えてました！

**Comment by Mokosu-bit** [comment]
宮本さんと同じく、モデルに移すのがいいと思います！

**Comment by konjikicity** [comment]
こちらscopeに切り出す対応ということでクローズいたします！
