### ISSUE TITLE
Eventモデルの作成

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#4]
### 概要
Eventモデルの作成とコントローラーの処理の実装。

### 各カラムのデータ型
- title
  - string
  - null: false
- description
  - string
  - null: false
- number_of_members
  - integer
  - null: false
- number_of_applicants　　←完全ランダム、完全希望制の場合はデフォルトの値`0`を利用する
  - integer
  - null: false
  - default: 0
- scheduled_date
  - datetime
  - null: false
- place
  - string
  - null: false
- pickable_mode
  - integer(enum)
  - null: false
  
### To Do
- [x] rails g scaffold
- [x] モデルの初期設定
- [x] コントローラーの処理
- [ ] モデルの関連付け

**Comment by jibiking** [comment]
### 備忘録
userとcategoryの外部キー設定は、それらのテーブルが作成されていないと設定できないので後ほど追加する。

**Comment by jibiking** [comment]
## Herokuにデプロイ時の備忘録
H14エラーが出ていたので[公式](https://devcenter.heroku.com/articles/error-codes#h14-no-web-dynos-running)の通り、```heroku ps:scale web=1```をしたらエラー解決しました。
Herokuデプロイ完了です！
