### ISSUE TITLE
日付の異常値入力を防ぐ

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#50]
## 概要
現状、どの月でも31日まで入力ができてイベント作成ができてしまう。
たとえば、2/30で登録すると、3/2（2/28の２日後）で登録されて意図しない挙動を引き起こす。
要改善
参考になりそうなやつ
[railsでカレンダー上に無い日付のバリデーションを行う時の注意点 \- Qiita](https://qiita.com/msky026/items/7a21203546eb50892c9f)

**Comment by tarakish** [comment]
## 対応
地引さんと口頭確認済み
https://qiita.com/Holy-0116/items/0a6ae6a606ddc7458e4a
こちらの記事にあるように日付をカレンダー形式の入力フォームにすれば、
開発ツールなどでparamsをいじらない限り入力を防げるためこの方法を採用します！（runteq生の良心を信じてバリデーションはかけない）
作業は地引さん @jibiking にお願いしてます！🙏🏻

**Comment by jibiking** [comment]
#46 で解決済み
