### ISSUE TITLE
mail通知機能を実装する

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#52]
## 概要
github認証で取得したemail宛に通知する機能を実装する。
実装方法はaction_mailerを使いそう。
通知タイミングとしては、
- ユーザー登録完了時
- ランダム抽出時
- 参加予定イベントの開始〇〇時間前

の３パターンが考えられますが、なにか追記あればコメントください！

## ToDo

- [x] ユーザー登録時にメールを送信する
- [x] ランダム抽出時(pickableされた時)にメールを送信する
- [x] 参加イベントの開始〇〇時間前にメールを送信する

**Comment by konjikicity** [comment]
ユーザー登録時にメールが送信されることを確認
![0c7b59e004d60099d72c1d71ecd79542](https://user-images.githubusercontent.com/82688205/162666629-9bd246ab-07d8-4cbd-9760-6d75ee27eeb4.png)

**Comment by konjikicity** [comment]
pickable時メールが送信されることを確
![844ea7a68627b307417f2c9a83b2d574](https://user-images.githubusercontent.com/82688205/162667167-2a59b3dd-45cf-4af1-939e-ce892089b8a0.png)
認

**Comment by konjikicity** [comment]
イベント開始前にメールが送信されることを確認
イベント作成 イベント開始時刻が20:00時の場合
![b5eb7572f1e37fa0676ce72cea54141f](https://user-images.githubusercontent.com/82688205/162667418-8887fb28-c94c-456d-9f31-1818bdb41a1c.png)

**Comment by konjikicity** [comment]
イベントキャンセル時参加者にメールが送信されることを確認
![db84150d52051328924fe124acb37b9e](https://user-images.githubusercontent.com/82688205/162667567-63bc6d43-892b-4f53-99c4-eb0fedcdae9e.png)
