### ISSUE TITLE
エラーメッセージを共通化する

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#64]
## 概要
エラーメッセージ表示部分が、現状各モデルの_formテンプレートに定義されているためこちらを共通化する。
参考は[基礎編カリキュラム](https://school.runteq.jp/v2/curriculums/rails_basic/chapters/11)

**Comment by konjikicity** [comment]
エラーメッセージの表示
イベント
![fad346b24a9cb879509fea6809ed1112](https://user-images.githubusercontent.com/82688205/163524623-6175d307-dfbf-40c1-9248-52f526586123.png)

ユーザー
![426defa00b63ba540e7095f003eebff7](https://user-images.githubusercontent.com/82688205/163524770-bfb5f333-bf0a-463e-b8ec-1d93840a628b.png)
