### ISSUE TITLE
pickable発動時にすでに参加しているユーザーをハジく

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#65]
## 概要
数名参加済みの場合にpickableを発動した際に、すでに参加しているユーザーも対象に入ってしまっているので
参加済みのユーザーが抽出されるとおそらくエラーが出る（未確認）
pickable#createの下記コードの前に参加済みユーザーを除外する処理を挟むことで解決できそう
```ruby
target_users.delete(current_user)
```

perticipated_users = target_users.event.participation ←イメージ（これは違う）
target_users.delete(〇〇)←〇〇に入れる

**Comment by Mokosu-bit** [comment]
現段階ではPickableの発動を一度限りにする（発動後、ボタンを消す or 押せない）考えのため、この問題が起こることはないですが、今後の実装で発動回数を制限しないようにすることがあれば、解決しておいたほうが良さそう！

#### Pickable発動を一度限りにする理由
制限しないと現状ではキャンセルしても何度でもPickableされるため。

**Comment by tarakish** [comment]
追記AZMS！
１点補足です！
> 現段階ではPickableの発動を一度限りにする（発動後、ボタンを消す or 押せない）考えのため、この問題が起こることはないですが…

発動タイミングが作成時のみなら問題ないですが、ある程度参加者が集まってからpickableを発動する場合は現状でも
この問題が起こるかと思います！（旧pickable機能の一部希望制のパターン）

**Comment by Mokosu-bit** [comment]
補足AZMS！

確かにそうですね！
#61 とまとめて対応します！
