### ISSUE TITLE
GitHub認証の挙動を確認する（？）

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#72]
## 概要
4/10の夕方ごろに、safariからherokuのpickableにログインした際に下記のような表示になっていたため、
確認していただきこちらと同じであれば、表示を変えたほうが良さそう。
<img width="996" alt="スクリーンショット 2022-04-10 17 56 55" src="https://user-images.githubusercontent.com/71510236/162626707-a4679c2d-c451-4162-81f1-f70e4beb06e0.png">

**Comment by konjikicity** [comment]
自分の携帯からsafariでherokuのpickableにログインしようとするとこんな感じでした
![IMG_0452](https://user-images.githubusercontent.com/82688205/162673055-9d4178fa-1c88-4fd7-bf3a-cde6aec38f2b.PNG)
今のとこ原因不明ですがsafariが影響してるんですかね....
