### ISSUE TITLE
github認証時の表示について

### ISSUE THREAD

**Issue by tarakish** [running-23/pickable#76]
## 概要
gituhub認証時に表示される
- アイコン
- アプリ名

などを調整する。

**Comment by konjikicity** [comment]
設定一応できていますが
少し画像が小さく表示されてしまっているので改善できないか調べています!
![c61e61d0fdc0ca7ee2651e8e11dcc54e](https://user-images.githubusercontent.com/82688205/163715923-4c9ae611-bf87-40fd-8f7d-b306458793be.png)

**Comment by konjikicity** [comment]
<img src="https://user-images.githubusercontent.com/82688205/163751335-d5377367-736e-4239-a300-fcc09f13a054.png" width="600px">
現在このような形で表示されます。説明追加していますが、認証画面では出ないようです。

**Comment by tarakish** [comment]
説明出ないんですね…知らなかったです🤔
お手数おかけしました！
画像があるだけでも違うと思うので、自分はこれで大丈夫だと思います！

**Comment by Mokosu-bit** [comment]
いいと思います！
変更AZMS！

**Comment by jibiking** [comment]
いい感じだと思います！
AZMS !!!!!!!!
